# Dataset settings
dataset:
  name: CelebAMaskHQ
  root: ../../data/CelebAMask-HQ
  num_workers: auto
  pin_memory: True
  normalize_mean: [0.5, 0.5, 0.5]
  normalize_std: [0.5, 0.5, 0.5]

# Model definitions (shape: [h, w])
BiSeNet:
  batch_size: 128
  epoch: 100
  criterion:
    name: CrossEntropyLoss
  aux_factor:
  optimizer:
    name: RAdam
    lr: 0.0005
    weight_decay: 0
  scheduler:
    name: PolyLR
    power: 0.9
  augmentation:
    RandomResize:
      min_scale: 1.0
      max_scale: 1.2
    RandomCrop:
      size: [512, 512]
    RandomRotation:
      degrees: [-18, 18]
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0
    RandomHorizontalFlip:
  pretrained_weights: weights/BiSeNet_best_mean_f1.pth

EAGRNet:
  batch_size: 64
  epoch: 100
  criterion:
    name: CrossEntropyLoss
  aux_factor:
  optimizer:
    name: RAdam
    lr: 0.001
    weight_decay: 0
  scheduler:
    name: PolyLR
    power: 0.9
  augmentation:
    RandomResize:
      min_scale: 1.0
      max_scale: 1.2
    RandomCrop:
      size: [512, 512]
    RandomRotation:
      degrees: [-18, 18]
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0
    RandomHorizontalFlip:
  pretrained_weights: weights/EAGRNet_best_mean_f1.pth

UNet:
  batch_size: 64
  epoch: 100
  criterion:
    name: CrossEntropyLoss
  aux_factor:
  optimizer:
    name: RAdam
    lr: 0.001
    weight_decay: 0
  scheduler:
    name: PolyLR
    power: 0.9
  augmentation:
    RandomResize:
      min_scale: 1.0
      max_scale: 1.2
    RandomCrop:
      size: [512, 512]
    RandomRotation:
      degrees: [-18, 18]
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0
    RandomHorizontalFlip:
  pretrained_weights: weights/UNet_best_mean_f1.pth