# Dataset settings
dataset:
  name: Lane
  root: ../../data/Lane
  num_workers: auto
  pin_memory: True
  normalize_mean: [0.5, 0.5, 0.5]
  normalize_std: [0.5, 0.5, 0.5]
  class_weight: # [0.0013, 0.1288, 1.0, 4.0468]

# Model definitions (shape: [h, w])
BiSeNet:
  batch_size: 16
  epoch: 100
  criterion:
    name: FocalLoss
    alpha: 0.25
    gamma: 2
    label_smoothing: 0.1
  aux_factor:
  optimizer:
    name: RAdam
    lr: 0.001
    weight_decay: 0
  scheduler:
    name: PolyLR
    power: 0.9
  augmentation:
    RandomCrop:
      size: [576, 1024]
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0
    RandomHorizontalFlip:
  pretrained_weight: weights/BiSeNet_latest.pth

DeepLabV3:
  backbone: ResNeSt50
  batch_size: 16
  epoch: 100
  criterion:
    name: FocalLoss
    alpha: 0.25
    gamma: 2
    label_smoothing: 0.1
  aux_factor:
  optimizer:
    name: RAdam
    lr: 0.001
    weight_decay: 0
  scheduler:
    name: PolyLR
    power: 0.9
  augmentation:
    RandomCrop:
      size: [576, 1024]
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0
    RandomHorizontalFlip:
  pretrained_weight: weights/DeepLabV3_latest.pth

RegSeg:
  batch_size: 32
  epoch: 100
  criterion:
    name: CrossEntropyLoss
    label_smoothing: 0.1
  aux_factor:
  optimizer:
    name: NovoGrad
    lr: 0.05
    weight_decay: 0.0001
  scheduler:
    name: PolyLR
    power: 0.9
  augmentation:
    RandomCrop:
      size: [576, 1024]
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0
    RandomHorizontalFlip:
  pretrained_weight: weights/RegSeg_latest.pth

SFNet:
  backbone: ResNet18
  batch_size: 32
  epoch: 100
  criterion:
    name: FocalLoss
    alpha: 0.25
    gamma: 2
    label_smoothing: 0.1
  aux_factor:
  optimizer:
    name: RAdam
    lr: 0.001
    weight_decay: 0.0001
  scheduler:
    name: PolyLR
    power: 0.9
  augmentation:
    RandomCrop:
      size: [576, 1024]
    ColorJitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0
    RandomHorizontalFlip:
  pretrained_weight: weights/SFNet_latest.pth
