# Dataset settings
dataset:
  name: NIA
  root: ../../data/NIA
  num_workers: 1
  pin_memory: True
  normalize_mean: [0.5, 0.5, 0.5]
  normalize_std: [0.5, 0.5, 0.5]
  class_weight:

# Model definitions (shape: [h, w])
EAGR:
  batch_size: 16
  epoch: 40
  criterion:
    name: CrossEntropyLoss
    label_smoothing: 0
  aux_factor:
  optimizer:
    name: RAdam
    lr: 0.001
    weight_decay: 0
  scheduler:
    name: PolyLR
    power: 0.9
  augmentation:
    RandomRotation:
      degrees: [-10, 10]
    ColorJitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0
    RandomHorizontalFlip:
  pretrained_weight: weights/EAGRNet_best_mean_f1.pth
