train:
  amp_enabled: True
  ddp_find_unused_parameters: False
  optimizer_zero_grad_set_to_none: True
  reproducibility: True
  reproducibility_seed: 0
  resume_training: False
  resume_training_checkpoint: # path